#--------------------------------------------
# File Name:   docker-build-push.yml
# Description: Automates image build and push
# Author:      Monica Dhieu
#--------------------------------------------

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:api-latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:buildcache-api
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:buildcache-api,mode=max

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:web-latest
          
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:buildcache-web
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nyc-train-mobility-app:buildcache-web,mode=max

